org: ezeikel
app: black-history-api
service: apollo-lambda
variablesResolutionMode: 20210326

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  environment:
    DATABASE_URL: ${ssm:/black-history/keys/mongodb}
  lambdaHashingVersion: 20201221

plugins:
  - serverless-domain-manager
  - serverless-plugin-typescript
  - serverless-offline

custom:
  customDomain:
    domainName: api.blackhistory.fyi
    basePath: graphql
    createRoute53Record: true
  serverless-offline:
    printOutput: true
    prefix: graphql

functions:
  graphql:
    handler: src/handlers/graphql.handler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
