org: ezeikel
app: black-history-api
service: apollo-lambda
variablesResolutionMode: 20210326

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  environment:
    DATABASE_URL: ${ssm:/black-history/keys/mongodb}
  lambdaHashingVersion: 20201221

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.blackhistory.fyi
    basePath: graphql
    createRoute53Record: true
  serverless-offline:
    printOutput: true
    prefix: graphql
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packagerOptions:
      scripts: # this is the magic
        - npx prisma generate
    packager: 'yarn' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

functions:
  graphql:
    handler: src/handlers/graphql.handler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
