org: ezeikel
app: black-history-api
service: apollo-lambda
variablesResolutionMode: 20210326

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  environment:
    DATABASE_URL: ${ssm:/black-history/keys/mongodb}
    SENTRY_DSN: ${ssm:/black-history/keys/sentry}
    CLOUDINARY_KEY: ${ssm:/black-history/keys/cloudinary/key}
    CLOUDINARY_SECRET: ${ssm:/black-history/keys/cloudinary/secret}
    APP_SECRET: MHXoALvMkPk5v2dAVwLBdnmeXioX79OVn6pElXqdld21IIVHA6LSvTzq8oY3tYRMkWBXCEQQCYt84ThFZyxmq7TvstA1Ne0UALU6+EJb6uQh+cUYLhBx3TrgL+gbvO2eNoKCRG832eXKsoYvmZ8nZ9J3xgDbA6QPhZRHOYw0PQ/kMT9xJt5faYiJ0TkuiyQomeuJgPHa70jgIx+e2fFSgbIBCIf3355QMulp9O7Zzt0uUL/eA5Lqv6sU2eNCExvAZPMFup5FLGp9fjM48oXqeJGgLxL7JHytHB/6dIu71WVIi/VeUH4HsUTrh/P2pxm0Y2IgnugTK/KD9/6LL8QAYw== # TODO: store this in AWS
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  lambdaHashingVersion: 20201221

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.blackhistory.fyi
    basePath: graphql
    createRoute53Record: true
  serverless-offline:
    printOutput: true
    prefix: graphql
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packagerOptions:
      scripts: # this is the magic
        - npx prisma generate
    packager: "yarn" # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

functions:
  graphql:
    handler: src/handlers/graphql.handler
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
